FROM __BASEIMAGE_ARCH__/alpine:latest

LABEL name='CertBot'
LABEL version='0.2'
LABEL description="Certbot on Alpine"
LABEL org.ctrlaltdev.vendor='ctrlaltdev'

__CROSS_COPY qemu-__QEMU_ARCH__-static /usr/bin/

RUN set -x && apk --no-cache add certbot

VOLUME /etc/letsencrypt /var/lib/letsencrypt

ENTRYPOINT [ "certbot" ]